let character = {
  name: '',
  health() {
    return (ballsSkill * 1.05)
  },
  mana: 100,
  damage: 0,
  attackSpeed: 100,
  critChance: 10,
  critDmg: 10,
  overpower: 10,

  poisonDmg: 10,
  frostDmg: 10,
  fireDmg: 10,
  shadowDmg: 10,
  sorceryDmg: 10,
  curseDmg: 10,
  baneDmg: 10,

  thorns: 10,
  healthPerSecond: 10,
  manaPerSecond: 10,
  healthOnHit: 10,
  ManaOnHit: 10,
  potionEffectiveness: 10,
  moveSpeed: 10,
};

let warlockMastery = {
  fire: {
    destruction: {
      name: "Destruction",
      description: `+${warlockMastery.fire.destruction.currentRank}% Reach.`,
      type: ['fire'],
      skillType: 'passive',
      multiplier: 1,
      masteryReq: 0,
      currentRank: 0,
      maxRank: 20,
    },
    ignition: {
      name: "Ignition",
      description: `${warlockMastery.fire.ignition.multiplier * warlockMastery.fire.ignition.currentRank} increased damage of *Firebomb* and *Flashfire.`,
      type: ['fire'],
      skillType: 'passive',
      multiplier: 2
      masteryReq: 5,
      currentRank: 0,
      maxRank: 99999,
    },
    incendiarySpells: {
      name: "Incendiary Spells",
      description: `+${warlockMastery.fire.incendiarySpells.multiplier * warlockMastery.fire.incendiarySpells.currentRank}% chance to trigger *Combustion*.`,
      type: ['fire'],
      skillType: 'passive',
      multiplier: 1,
      masteryReq: 10,
      currentRank: 0,
      maxRank: 20,
    },
    animosity: {
      name: "Animosity",
      description: `${warlockMastery.fire.animosity.multiplier * warlockMastery.fire.animosity.currentRank}% increased *Detonation*, *Hell Pit*, and *Heat Wave* damage per rank.`,
      type: ['fire'],
      skillType: 'passive',
      multiplier: 2,
      masteryReq: 15,
      currentRank: 0,
      maxRank: 99999,
    },
    blastWave: {
      name: "Blast Wave",
      description: `${warlockMastery.fire.blastWave.multiplier * warlockMastery.fire.blastWave.currentRank}% increased damage of *Combustion*.`,
      type: ['fire'],
      skillType: 'passive',
      multiplier: 5,
      masteryReq: 20,
      currentRank: 0,
      maxRank: 100,
    },
    pyromaniac: {
      name: "Pyromaniac",
      description: `${warlockMastery.fire.pyromaniac.multiplier * warlockMastery.fire.pyromaniac.currentRank}% increased *Hellfire*, *Firenova*, and *Wall of Fire* damage.`,
      type: ['fire'],
      skillType: 'passive',
      multiplier: 2,
      masteryReq: 25,
      currentRank: 0,
      maxRank: 99999,
    },
    burningHells: {
      name: "Burning Hells",
      description: `${warlockMastery.fire.burningHells.multiplier * warlockMastery.fire.burningHells.currentRank}% increased damage of *Flaming Hells*.`,
      type: ['fire'],
      skillType: 'passive',
      multiplier: 5,
      masteryReq: 30,
      currentRank: 0,
      maxRank: 100,
    },
    hellRaiser: {
      name: "Hell Raiser",
      description: `${warlockMastery.fire.hellRaiser.multiplier * warlockMastery.fire.hellRaiser.currentRank}% increased *Inferno*, *Meteor*, and *Fire Storm* damage per rank.`,
      type: ['fire'],
      skillType: 'passive',
      multiplier: 2,
      masteryReq: 35,
      currentRank: 0,
      maxRank: 99999,
    },
    diabolist: {
      name: "Diabolist",
      description: `${warlockMastery.fire.diabolist.multiplier * warlockMastery.fire.diabolist.currentRank}% reduced cool down of *Infernal Demon* and *Demon Spawn*.`,
      type: ['fire'],
      skillType: 'passive',
      multiplier: 3,
      masteryReq: 40,
      currentRank: 0,
      maxRank: 20,
    },
	},
  shadow: {
    soulDrain: {
      name: "Soul Drain",
      description: `${warlockMastery.shadow.soulDrain.currentRank}% Mana.`,
      type: ['Shadow'],
      skillType: 'passive',
      multiplier: 1,
      masteryReq: 0,
      currentRank: 0,
      maxRank: 20,
    },
    necromancy: {
      name: "Necromancy",
      description: `${warlockMastery.shadow.necromancy.currentRank * warlockMastery.shadow.necromancy.multiplier}% increased damage of *Screaming Skull* and *Hand of Death*.`,
      type: ['Shadow'],
      skillType: 'passive',
      multiplier: 2,
      masteryReq: 5,
      currentRank: 0,
      maxRank: 99999,
    },
    deathblow: {
      name: "Deathblow",
      description: `${warlockMastery.shadow.deathblow.currentRank}% chance to trigger *Sudden Death*.`,
      type: ['Shadow'],
      skillType: 'passive',
      multiplier: 1,
      masteryReq: 10,
      currentRank: 0,
      maxRank: 10,
    },
    dontFearTheReaper: {
      name: "Don't Fear The Reaper",
      description: `${warlockMastery.shadow.dontFearTheReaper.currentRank * warlockMastery.shadow.dontFearTheReaper.multiplier}% increased damage of *Life Reap*, *Curse of Woe*, and *Grave Blast*.`,
      type: ['Shadow'],
      skillType: 'passive',
      multiplier: 2,
      masteryReq: 15,
      currentRank: 0,
      maxRank: 99999,
    },
    darkLust: {
      name: "Dark Lust",
      description: `${warlockMastery.shadow.darkLust.currentRank}% increased effect of *Masochism*.`,
      type: ['Shadow'],
      skillType: 'passive',
      multiplier: 1,
      masteryReq: 20,
      currentRank: 0,
      maxRank: 20,
    },
    agony: {
      name: "Agony",
      description: `${warlockMastery.shadow.agony.currentRank * warlockMastery.shadow.agony.multiplier}% increased damage of *Curse of Terror*, *Curse of Reckoning*, and *Bone Spears*.`,
      type: ['Shadow'],
      skillType: 'passive',
      multiplier: 2,
      masteryReq: 25,
      currentRank: 0,
      maxRank: 99999,
    },
    sorrow: {
      name: "Sorrow",
      description: `${warlockMastery.shadow.sorrow.currentRank * warlockMastery.shadow.sorrow.multiplier}% increased damage of *Desecration*.`,
      type: ['Shadow'],
      skillType: 'passive',
      multiplier: 5,
      masteryReq: 30,
      currentRank: 0,
      maxRank: 100,
    },
    boneCharmer: {
      name: "Bone Charmer",
      description: `${warlockMastery.shadow.boneCharmer.currentRank * warlockMastery.shadow.boneCharmer.multiplier}% increased damage of *Bone Scythe*, *Bone Storm*, and *Bone Curse*.`,
      type: ['Shadow'],
      skillType: 'passive',
      multiplier: 2,
      masteryReq: 35,
      currentRank: 0,
      maxRank: 99999,
    },
    darkLord: {
      name: "Dark Lord",
      description: `${warlockMastery.shadow.darkLord.currentRank * warlockMastery.shadow.darkLord.multiplier}% reduced cooldown of *Death Knight*, *Vampire Lord*, and *Raise Dead*.`,
      type: ['Shadow'],
      skillType: 'passive',
      multiplier: 3,
      masteryReq: 40,
      currentRank: 0,
      maxRank: 5,
    },
  },
  frost: {
    skullShatter: {
      name: "Skull Shatter",
      description: `+${warlockMastery.frost.skullShatter.currentRank}% Critical Hit Damage.`,
      type: ['Frost'],
      skillType: 'passive',
      multiplier: 1,
      masteryReq: 0,
      currentRank: 0,
      maxRank: 20,
    },
    eternalCold: {
      name: "Eternal Cold",
      description: `${warlockMastery.frost.eternalCold.currentRank * warlockMastery.frost.eternalCold.multiplier}% increased damage of *Frost Spear* and *Frozen Flash*.`,
      type: ['Frost'],
      skillType: 'passive',
      multiplier: 2,
      masteryReq: 5,
      currentRank: 0,
      maxRank: 99999,
    },
    frozenCorpses: {
      name: "Frozen Corpses",
      description: `+${warlockMastery.frost.frozenCorpses.currentRank}% chance to trigger *Corpse Shatter*.`,
      type: ['Frost'],
      skillType: 'passive',
      multiplier: 1,
      masteryReq: 10,
      currentRank: 0,
      maxRank: 20,
    },
    frozenSkull: {
      name: "Frozen Skull",
      description: `${warlockMastery.frost.frozenSkull.currentRank * warlockMastery.frost.frozenSkull.multiplier}% increased damage of *Serrated Spears*, *Skull Bomb*, and *Ruin*.`,
      type: ['Frost'],
      skillType: 'passive',
      multiplier: 2,
      masteryReq: 15,
      currentRank: 0,
      maxRank: 99999,
    },
    iceShield: {
      name: "Ice Shield",
      description: `${warlockMastery.frost.iceShield.currentRank * warlockMastery.frost.iceShield.multiplier}% increased damage absorbed by *Frozen Veil*.`,
      type: ['Frost'],
      skillType: 'passive',
      multiplier: 5,
      masteryReq: 20,
      currentRank: 0,
      maxRank: 10,
    },
    deathChill: {
      name: "Death Chill",
      description: `${warlockMastery.frost.deathChill.currentRank * warlockMastery.frost.deathChill.multiplier}% increased damage of *Frigid Star*, *Frost Nova*, and *Frozen Fate*.`,
      type: ['Frost'],
      skillType: 'passive',
      multiplier: 2,
      masteryReq: 25,
      currentRank: 0,
      maxRank: 99999,
    },
    freezingDeath: {
      name: "Freezing Death",
      description: `${warlockMastery.frost.freezingDeath.currentRank * warlockMastery.frost.freezingDeath.multiplier}% increased damage of *Cold Death*.`,
      type: ['Frost'],
      skillType: 'passive',
      multiplier: 5,
      masteryReq: 30,
      currentRank: 0,
      maxRank: 100,
    },
    coldPassion: {
      name: "Cold Passion",
      description: `${warlockMastery.frost.coldPassion.currentRank * warlockMastery.frost.coldPassion.multiplier}% increased damage of *Comet*, *Deathly Barrage*, and *Curse of Doom*.`,
      type: ['Frost'],
      skillType: 'passive',
      multiplier: 2,
      masteryReq: 35,
      currentRank: 0,
      maxRank: 99999,
    },
    deeathsGift: {
      name: "Death's Gift",
      description: `${warlockMastery.frost.deeathsGift.currentRank * warlockMastery.frost.deeathsGift.multiplier}% reduced cooldown of *Frozen Death* and *Lich Form*.`,
      type: ['Frost'],
      skillType: 'passive',
      multiplier: 3,
      masteryReq: 40,
      currentRank: 0,
      maxRank: 5,
    },
  },
  poison: {
    rapidInfections: {
      name: "Rapid Infections",
      description: `+${warlockMastery.poison.rapidInfections.currentRank}% Attack Speed.`,
      type: ['Poison'],
      skillType: 'passive',
      multiplier: 1,
      masteryReq: 0,
      currentRank: 0,
      maxRank: 20,
    },
    rottingFlesh: {
      name: "Rotting Flesh",
      description: `${warlockMastery.poison.rottingFlesh.currentRank * warlockMastery.poison.rottingFlesh.multiplier}% increased damage of *Poison Bolt* and *Blood Curse*.`,
      type: ['Poison'],
      skillType: 'passive',
      multiplier: 2,
      masteryReq: 5,
      currentRank: 0,
      maxRank: 99999,
    },
    taint: {
      name: "Taint",
      description: `${warlockMastery.poison.taint.currentRank}% increased chance to trigger *Outbreak*.`,
      type: ['Poison'],
      skillType: 'passive',
      multiplier: 1,
      masteryReq: 10,
      currentRank: 0,
      maxRank: 20,
    },
    contamination: {
      name: "Contamination",
      description: `${warlockMastery.poison.contamination.currentRank * warlockMastery.poison.contamination.multiplier}% increased damage of *Poison Skull*, *Plauge*, and *Flesh Rot*.`,
      type: ['Poison'],
      skillType: 'passive',
      multiplier: 2,
      masteryReq: 15,
      currentRank: 0,
      maxRank: 20,
    },
    infusedBlood: {
      name: "Infused Blood",
      description: `${warlockMastery.poison.infusedBlood.currentRank}% increased chance to trigger *Living Blood*.`,
      type: ['Poison'],
      skillType: 'passive',
      multiplier: 1,
      masteryReq: 20,
      currentRank: 0,
      maxRank: 20,
    },
    defilement: {
      name: "Defilement",
      description: `${warlockMastery.poison.defilement.currentRank * warlockMastery.poison.defilement.multiplier}% increased damage of *Poison Nova*, *Bane of the Dead*, and *Mind Torture*.`,
      type: ['Poison'],
      skillType: 'passive',
      multiplier: 2,
      masteryReq: 25,
      currentRank: 0,
      maxRank: 99999,
    },
    infectionsDisease: {
      name: "Infectious Disease",
      description: `${warlockMastery.poison.infectionsDisease.currentRank * warlockMastery.poison.infectionsDisease.multiplier}% increased damage of *Infection*.`,
      type: ['Poison'],
      skillType: 'passive',
      multiplier: 5,
      masteryReq: 30,
      currentRank: 0,
      maxRank: 100,
    },
    sickness: {
      name: "Sickness",
      description: `${warlockMastery.poison.sickness.currentRank * warlockMastery.poison.sickness.multiplier}% increased damage of *Vile Pool*, *Affliction*, and *Corruption*.`,
      type: ['Poison'],
      skillType: 'passive',
      multiplier: 2,
      masteryReq: 35,
      currentRank: 0,
      maxRank: 99999,
    },
    malignancy: {
      name: "Malignancy",
      description: `${warlockMastery.poison.malignancy.currentRank * warlockMastery.poison.malignancy.multiplier}% reduced cooldown of *Plague Lord* and *Cloak of Infection*.`,
      type: ['Poison'],
      skillType: 'passive',
      multiplier: 3,
      masteryReq: 40,
      currentRank: 0,
      maxRank: 5,
    },
  },
  curse: {
    soulDrinker: {
      name: "Soul Drinker",
      description: `+${warlockMastery.curse.soulDrinker.currentRank} Mana.`,
      type: ['Ethereal'],
      skillType: 'passive',
      multiplier: 10,
      masteryReq: 0,
      currentRank: 0,
      maxRank: 99999,
    },
    jinxed: {
      name: "Jinxed",
      description: `+${warlockMastery.curse.jinxed.currentRank * warlockMastery.curse.jinxed.multiplier}% Effect Duration.`,
      type: ['Ethereal'],
      skillType: 'passive',
      multiplier: 2,
      masteryReq: 5,
      currentRank: 0,
      maxRank: 10,
    },
    soulVessels: {
      name: "Soul Vessels",
      description: `+${warlockMastery.curse.soulVessels.currentRank} Maximum Souls.`,
      type: ['Ethereal'],
      skillType: 'passive',
      multiplier: 1,
      masteryReq: 10,
      currentRank: 0,
      maxRank: 5,
    },
    frenziedMinions: {
      name: "Frenzied Minions",
      description: `+${warlockMastery.curse.frenziedMinions.currentRank}% Companion Damage.`,
      type: ['Ethereal'],
      skillType: 'passive',
      multiplier: 1,
      masteryReq: 0,
      currentRank: 15,
      maxRank: 30,
    },
    improvedPotions: {
      name: "Improved Potions",
      description: `+${warlockMastery.curse.improvedPotions.currentRank * warlockMastery.curse.improvedPotions.multiplier}% Potion Effectiveness.`,
      type: ['Ethereal'],
      skillType: 'passive',
      multiplier: 3,
      masteryReq: 20,
      currentRank: 0,
      maxRank: 15,
    },
    enhancedResistance: {
      name: "Enhanced Resistance",
      description: `+${warlockMastery.curse.enhancedResistance.currentRank}% Resistance to all Elements.`,
      type: ['Ethereal'],
      skillType: 'passive',
      multiplier: 1,
      masteryReq: 25,
      currentRank: 0,
      maxRank: 10,
    },
    overpowerSkill: {
      name: "Overpower",
      description: `+${warlockMastery.curse.overpowerSkill.currentRank}% Overpower.`,
      type: ['Ethereal'],
      skillType: 'passive',
      multiplier: 10,
      masteryReq: 30,
      currentRank: 0,
      maxRank: 10,
    },
    elementalPowerSkill: {
      name: "Elemental Power",
      description: `+${warlockMastery.curse.elementalPowerSkill.currentRank}% to all Damage Elements.`,
      type: ['Ethereal'],
      skillType: 'passive',
      multiplier: 1,
      masteryReq: 35,
      currentRank: 0,
      maxRank: 20,
    },
    deathSpeaker: {
      name: "Death Speaker",
      description: `+${warlockMastery.curse.deathSpeaker.currentRank * warlockMastery.curse.deathSpeaker.multiplier}% Curse Skill Damage.`,
      type: ['Ethereal'],
      skillType: 'passive',
      multiplier: 2,
      masteryReq: 40,
      currentRank: 0,
      maxRank: 10,
    },
  },
  bane: {
    darkBlood: {
      name: "Dark Blood",
      description: `+${warlockMastery.bane.darkBlood.currentRank * warlockMastery.bane.darkBlood.multiplier} Health.`,
      type: ['Ethereal'],
      skillType: 'passive',
      multiplier: 10,
      masteryReq: 0,
      currentRank: 0,
      maxRank: 99999,
    },
    deathsMarch: {
      name: "Death's March",
      description: `+${warlockMastery.bane.deathsMarch.currentRank}% Movement Speed.`,
      type: ['Ethereal'],
      skillType: 'passive',
      multiplier: 1,
      masteryReq: 5,
      currentRank: 0,
      maxRank: 10,
    },
    soulPrison: {
      name: "Soul Prison",
      description: `+${warlockMastery.bane.soulPrison.currentRank * warlockMastery.bane.soulPrison.multiplier}% Soul Duration.`,
      type: ['Ethereal'],
      skillType: 'passive',
      multiplier: 5,
      masteryReq: 10,
      currentRank: 0,
      maxRank: 10,
    },
    unholyRenewal: {
      name: "Unholy Renewal",
      description: `+${warlockMastery.bane.unholyRenewal.currentRank}% Health Regeneration.`,
      type: ['Ethereal'],
      skillType: 'passive',
      multiplier: 5,
      masteryReq: 15,
      currentRank: 0,
      maxRank: 30,
    },
    improvedPotions: {
      name: "Improved Potions",
      description: `+${warlockMastery.bane.improvedPotions.currentRank * warlockMastery.bane.improvedPotions.multiplier}% Potion Effectiveness.`,
      type: ['Ethereal'],
      skillType: 'passive',
      multiplier: 3,
      masteryReq: 20,
      currentRank: 0,
      maxRank: 15,
    },
    enhancedResistance: {
      name: "Enhanced Resistance",
      description: `+${warlockMastery.bane.enhancedResistance.currentRank}% Resistance to all Elements.`,
      type: ['Ethereal'],
      skillType: 'passive',
      multiplier: 1,
      masteryReq: 25,
      currentRank: 0,
      maxRank: 10,
    },
    overpowerSkill: {
      name: "Overpower",
      description: `+${warlockMastery.bane.overpowerSkill.currentRank}% Overpower.`,
      type: ['Ethereal'],
      skillType: 'passive',
      multiplier: 10,
      masteryReq: 30,
      currentRank: 0,
      maxRank: 10,
    },
    elementalPowerSkill: {
      name: "Elemental Power",
      description: `+${warlockMastery.bane.elementalPowerSkill.currentRank}% to all Damage Elements.`,
      type: ['Ethereal'],
      skillType: 'passive',
      multiplier: 1,
      masteryReq: 35,
      currentRank: 0,
      maxRank: 20,
    },
    battleMage: {
      name: "Battle Mage",
      description: `+${warlockMastery.bane.battleMage.currentRank}% Bane Skill Damage.`,
      type: ['Ethereal'],
      skillType: 'passive',
      multiplier: 2,
      masteryReq: 40,
      currentRank: 0,
      maxRank: 10,
    },
  },
  sorcery: {
    spellpower: {
      name: "Spellpower",
      description: `+${warlockMastery.sorcery.spellpower.currentRank * warlockMastery.sorcery.spellpower.multiplier} Damage.`,
      type: ['Ethereal'],
      skillType: 'passive',
      multiplier: 10,
      masteryReq: 0,
      currentRank: 0,
      maxRank: 99999,
    },
    elementalOverload: {
      name: "Elemental Overload",
      description: `+${warlockMastery.sorcery.elementalOverload.currentRank}% Critical Hit Chance.`,
      type: ['Ethereal'],
      skillType: 'passive',
      multiplier: 1,
      masteryReq: 5,
      currentRank: 0,
      maxRank: 10,
    },
    heightenedMind: {
      name: "Heightened Mind",
      description: `+${warlockMastery.sorcery.heightenedMind.currentRank}% Evasion.`,
      type: ['Ethereal'],
      skillType: 'passive',
      multiplier: 1,
      masteryReq: 10,
      currentRank: 0,
      maxRank: 10,
    },
    loyalMinions: {
      name: "Loyal Minions",
      description: `+${warlockMastery.sorcery.loyalMinions.currentRank}% Companion Health.`,
      type: ['Ethereal'],
      skillType: 'passive',
      multiplier: 1,
      masteryReq: 15,
      currentRank: 0,
      maxRank: 30,
    },
    improvedPotions: {
      name: "Improved Potions",
      description: `+${warlockMastery.sorcery.improvedPotions.currentRank * warlockMastery.sorcery.improvedPotions.multiplier}% Potion Effectiveness.`,
      type: ['Ethereal'],
      skillType: 'passive',
      multiplier: 3,
      masteryReq: 20,
      currentRank: 0,
      maxRank: 15,
    },
    enhancedResistance: {
      name: "Enhanced Resistance",
      description: `+${warlockMastery.sorcery.enhancedResistance.currentRank}% Resistance to all Elements.`,
      type: ['Ethereal'],
      skillType: 'passive',
      multiplier: 1,
      masteryReq: 25,
      currentRank: 0,
      maxRank: 10,
    },
    overpowerSkill: {
      name: "Overpower",
      description: `+${warlockMastery.sorcery.overpowerSkill.currentRank}% Overpower.`,
      type: ['Ethereal'],
      skillType: 'passive',
      multiplier: 10,
      masteryReq: 30,
      currentRank: 0,
      maxRank: 10,
    },
    elementalPowerSkill: {
      name: "Elemental Power",
      description: `+${warlockMastery.sorcery.elementalPowerSkill.currentRank}% to all Damage Elements.`,
      type: ['Ethereal'],
      skillType: 'passive',
      multiplier: 1,
      masteryReq: 35,
      currentRank: 0,
      maxRank: 20,
    },
    masterSorcerer: {
      name: "Master Sorcerer",
      description: `+${warlockMastery.sorcery.masterSorcerer.currentRank * warlockMastery.sorcery.masterSorcerer.multiplier}% Sorcery Skill Damage.`,
      type: ['Ethereal'],
      skillType: 'passive',
      multiplier: 2,
      masteryReq: 40,
      currentRank: 0,
      maxRank: 10,
    },
  },
}
};
